server:
  port: 8035

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://127.0.0.1:8061/eureka/,http://127.0.0.1:8062/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


spring:
  boot:
    admin:
      client:
        prefer-ip: true # 解决windows下运行时无法识别主机名的问题
      url: http://localhost:8889 # 向服务端注册的地址
  security:
    user:
      name: "client"
      password: "client"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudshop?useSSL=false
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    filters: stat
    minEvictableIdleTimeMillis: 300000		# 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    refresh:
      refreshable: none
  rabbitmq:
    host: localhost
    port: 5672  #
    username: springcloud
    password: ligang

management:
  security:
    # 关闭 actuator 的身份验证
    enabled: false
   # 配置 actuator 的访问路径前缀
   # context-path: /monitor
    # actuator暴露接口使用的端口，为了和api接口使用的端口进行分离
   # port: 1111
  endpoints:
    web:
      exposure:
        include: "*"
  shutdown:
    enabled: true
  endpoint:
    health:
      show-details: always #默认是never


info:
  app:
   name: member(用户微服务)
   version: 1.0
   athor: ligang
   blog-url: www.chinabim.com
  